version: '1.0'
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: 'ybkuroki/go-webapp-sample'
    revision: master
    git: github
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    image_name: go-webapp-sample
    working_directory: ./
    tag: full
    dockerfile: Dockerfile
